swagger: "2.0"
info:
  description: "API desenvolvida para ser consumida pelo front e mobile da aplicação de rastreamento de pacotes desenvolvida para a disciplina de Sistemas Distribuídos."
  version: "1.0"
  title: "Rastreamento API"
host: "https://rastreamento-backend.herokuapp.com"
basePath: ""
tags:

- name: "API Rastreamento"
  description: ""

schemes:
- "HTTP protocol"
paths:
  /pacote:
    post:
      tags:
      - "API Rastreamento"
      summary: "Cadastrar Pacote"
      consumes:
        - "application/json"
      parameters:
      - name: "Content-Type"
        in: "header"
        type: "string"
        description: ""
        required: true
      responses:
        200:
          description: "successful operation"
    get:
      tags:
      - "API Rastreamento"
      summary: "Listar pacotes"
      responses:
        200:
          description: "successful operation"
  /pacote/ABCDE12345:
    get:
      tags:
      - "API Rastreamento"
      summary: "Pesquisar pacote"
      responses:
        200:
          description: "successful operation"
  /pacote/ABCDE12345/atualizacao:
    post:
      tags:
      - "API Rastreamento"
      summary: "Cadastrar atualização de status do pacote"
      consumes:
        - "application/json"
      parameters:
      - name: "Content-Type"
        in: "header"
        type: "string"
        description: ""
        required: true
      responses:
        200:
          description: "successful operation"
